language: r
pandoc_version: 2.3.1

before_install:
  - sudo apt-get update
  - sudo apt-get install python3


script:
  - bash build.sh
#  - Rscript -e 'devtools::install_github("juba/rmdformats")'


cache:
  packages: yes
  directories:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs # Book output directory
  on:
    branch: master
